# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './GUI/wikimedia/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(637, 512)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 380, 611, 51))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.crossvalidateButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.crossvalidateButton.setObjectName("crossvalidateButton")
        self.horizontalLayout_8.addWidget(self.crossvalidateButton)
        self.trainButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.trainButton.setObjectName("trainButton")
        self.horizontalLayout_8.addWidget(self.trainButton)
        self.predictButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.predictButton.setObjectName("predictButton")
        self.horizontalLayout_8.addWidget(self.predictButton)
        self.clearButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_8.addWidget(self.clearButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(220, 0, 401, 371))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.outputTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.outputTextEdit.setObjectName("outputTextEdit")
        self.verticalLayout_2.addWidget(self.outputTextEdit)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.inputTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.inputTextEdit.setObjectName("inputTextEdit")
        self.verticalLayout_2.addWidget(self.inputTextEdit)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 211, 61))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.classifierListWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_6)
        self.classifierListWidget.setObjectName("classifierListWidget")
        item = QtWidgets.QListWidgetItem()
        self.classifierListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.classifierListWidget.addItem(item)
        self.horizontalLayout_6.addWidget(self.classifierListWidget)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 132, 211, 61))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.datasetListWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_5)
        self.datasetListWidget.setObjectName("datasetListWidget")
        item = QtWidgets.QListWidgetItem()
        self.datasetListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.datasetListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.datasetListWidget.addItem(item)
        self.horizontalLayout_5.addWidget(self.datasetListWidget)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 70, 211, 61))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.analyzerListWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_4)
        self.analyzerListWidget.setObjectName("analyzerListWidget")
        item = QtWidgets.QListWidgetItem()
        self.analyzerListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.analyzerListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.analyzerListWidget.addItem(item)
        self.horizontalLayout_4.addWidget(self.analyzerListWidget)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 240, 191, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.maxGramLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.maxGramLineEdit.setObjectName("maxGramLineEdit")
        self.horizontalLayout_3.addWidget(self.maxGramLineEdit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 280, 191, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.minGramLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.minGramLineEdit.setObjectName("minGramLineEdit")
        self.horizontalLayout_2.addWidget(self.minGramLineEdit)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 330, 191, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.cv_foldsLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.cv_foldsLineEdit.setObjectName("cv_foldsLineEdit")
        self.horizontalLayout_7.addWidget(self.cv_foldsLineEdit)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 190, 191, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.maxFeatLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.maxFeatLineEdit.setObjectName("maxFeatLineEdit")
        self.horizontalLayout.addWidget(self.maxFeatLineEdit)
        self.label_2.raise_()
        self.horizontalLayoutWidget_8.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_6.raise_()
        self.horizontalLayoutWidget_5.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.label_2.raise_()
        self.maxFeatLineEdit.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_7.raise_()
        self.horizontalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 637, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuWikipedia_Talk_Data = QtWidgets.QMenu(self.menuBar)
        self.menuWikipedia_Talk_Data.setObjectName("menuWikipedia_Talk_Data")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuWikipedia_Talk_Data.addSeparator()
        self.menuBar.addAction(self.menuWikipedia_Talk_Data.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.crossvalidateButton.setText(_translate("MainWindow", "Cross Validate"))
        self.trainButton.setText(_translate("MainWindow", "Train"))
        self.predictButton.setText(_translate("MainWindow", "Predict"))
        self.clearButton.setText(_translate("MainWindow", "clear (output)"))
        self.label_7.setText(_translate("MainWindow", "output"))
        self.label.setText(_translate("MainWindow", "input"))
        self.label_6.setText(_translate("MainWindow", "classifier"))
        __sortingEnabled = self.classifierListWidget.isSortingEnabled()
        self.classifierListWidget.setSortingEnabled(False)
        item = self.classifierListWidget.item(0)
        item.setText(_translate("MainWindow", "LogisticRegression"))
        item = self.classifierListWidget.item(1)
        item.setText(_translate("MainWindow", "LinearSVC"))
        self.classifierListWidget.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("MainWindow", "dataset  "))
        __sortingEnabled = self.datasetListWidget.isSortingEnabled()
        self.datasetListWidget.setSortingEnabled(False)
        item = self.datasetListWidget.item(0)
        item.setText(_translate("MainWindow", "aggression"))
        item = self.datasetListWidget.item(1)
        item.setText(_translate("MainWindow", "attack"))
        item = self.datasetListWidget.item(2)
        item.setText(_translate("MainWindow", "toxicity"))
        self.datasetListWidget.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("MainWindow", "analyzer"))
        __sortingEnabled = self.analyzerListWidget.isSortingEnabled()
        self.analyzerListWidget.setSortingEnabled(False)
        item = self.analyzerListWidget.item(0)
        item.setText(_translate("MainWindow", "char"))
        item = self.analyzerListWidget.item(1)
        item.setText(_translate("MainWindow", "char_wb"))
        item = self.analyzerListWidget.item(2)
        item.setText(_translate("MainWindow", "word"))
        self.analyzerListWidget.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "max ngram             "))
        self.maxGramLineEdit.setText(_translate("MainWindow", "3"))
        self.label_3.setText(_translate("MainWindow", "min ngram              "))
        self.minGramLineEdit.setText(_translate("MainWindow", "1"))
        self.label_9.setText(_translate("MainWindow", "CV folds                 "))
        self.cv_foldsLineEdit.setText(_translate("MainWindow", "3"))
        self.label_2.setText(_translate("MainWindow", "max features          "))
        self.maxFeatLineEdit.setText(_translate("MainWindow", "1000"))
        self.menuWikipedia_Talk_Data.setTitle(_translate("MainWindow", "Wikipedia Talk Data"))

